apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
  labels:
    app: testdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testdeploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      containers:
        - name: testdeploy
          image: testdeploy.azurecr.io/testdeploy:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: testdeploy-service
  labels:
    app: testdeploy
spec:
  selector:
    app: testdeploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
