apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeploy
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      containers:
      - name: testdeploy
        image: testdeploy.azurecr.io/testdeploy:latest
        ports:
        - containerPort: 8080
