apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeploy
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      containers:
      - name: testdeploy
        image: testdeploy.azurecr.io/testdeploy:latest
        ports:
        - containerPort: 8080
apiVersion: v1
kind: Service
metadata:
  name: testdeploy-service
spec:
  type: LoadBalancer
  selector:
    app: testdeploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
